# Generated by Django 5.1.6 on 2025-03-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_Price',
            new_name='sale_price',
        ),
    ]
